<?php

	// Exit if accessed directly
	if ( ! defined( 'ABSPATH' ) ) exit;

	// register new post type into dashboard
	function smarty_consultation_custom_post_type() {
		$labels = array(
			'name'              => 'Consultations',
			'singular_name'     => 'Consultation',
			'menu_name'         => 'Consultations',
			'name_admin_bar'    => 'Consultation',
			'not_found'         => 'No Consultations Found',
		);
		$args = array(
			'labels'            => $labels,
			'show_ui'           => true,
			'show_in_menu'      => true,
			'capability_type'   => 'post',  // We Want to be as post not page
			'hierarchical'      => false,   // Because post can't be hierarchical so must put it false
			'menu_position'     => 26,
			'menu_icon'         => 'dashicons-phone',
			'supports'          => array( 'title', 'editor', 'author' )
		);
		// register post type
		register_post_type( 'smarty-consulting', $args );
	}
	add_action('init', 'smarty_consultation_custom_post_type');


	// Change Consultation Columns Name
	function smarty_set_consultation_columns( $columns ) {
		$newColumns = array();
		$newColumns['title']    = __('Consultation Type');
		$newColumns['message']  = __('Message');
		$newColumns['email']    = __('Email');
		$newColumns['date']     = __('Date');
		return $newColumns;
	}
	add_filter( 'manage_smarty-consulting_posts_columns', 'smarty_set_consultation_columns' );


	// Print Column Value For Consultation
	function smarty_consultation_column_value( $column, $post_id ) {
		switch ( $column ) {
			case 'message' :
				// in the loop the $post_id is already set and get_the_excerpt will know witch type of message will print
				echo get_the_excerpt();
				break;
			case 'email':
				$email = get_post_meta( $post_id, '_contact_email_value_key', true );
				echo '<a href="mailto:' . $email . '">' . $email . '</a>';
				break;
		}
	}
	add_action( 'manage_smarty-consulting_posts_custom_column', 'smarty_consultation_column_value', 10, 2 );


	// add email meta box
	function smarty_consultation_add_meta_box() {
		add_meta_box( 'consultation_email', __('User Email'), 'smarty_consultation_email_callback', 'smarty-consulting', 'side', 'default' );
	}
	add_action( 'add_meta_boxes', 'smarty_consultation_add_meta_box' );

	function smarty_consultation_email_callback( $post ) {

		wp_nonce_field( 'smarty_save_consultation_email_data', 'smarty_consultation_email_meta_box_nonce' );

		$value = get_post_meta( $post->ID, '_contact_email_value_key', true );
		// Print The input as wordpress theme build-in
		echo '<label for="smarty_consultation_email_field">' . __('User Email Address') . ': </label>';
		echo '<input type="email" id="smarty_consultation_email_field" name="smarty_consultation_email_field" value="' . esc_attr( $value ) . '" size="25" />';
	}

	// function to print the email inside our meta box and save the post
	function smarty_save_consultation_email_data( $post_id ) {
		// check if the nonce is not set in the $_POST Method
		if ( ! isset( $_POST['smarty_consultation_email_meta_box_nonce'] ) ) {
			return;
		}
		// check if the nonce is valid and nonce is generated by wordpress and not generated by and hacker or another user
		// sunset_save_contact_email_data: is the actual function that saving my meta box
		if ( ! wp_verify_nonce( $_POST['smarty_consultation_email_meta_box_nonce'], 'smarty_save_consultation_email_data' ) ) {
			return;
		}
		// check is a manual save or automatically save | prevent the wordpress from saving by him self the meta box
		if ( defined('DOING_AUTOSAVE') && DOING_AUTOSAVE ) {
			return;
		}
		// Check for user permission
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
		// check if our input name sunset_contact_email_field is in $_POST method
		if ( ! isset( $_POST['smarty_consultation_email_field'] ) ) {
			return;
		}
		// Retrieve the data
		$my_data = sanitize_text_field( $_POST['smarty_consultation_email_field'] );
		update_post_meta( $post_id, '_contact_email_value_key', $my_data );
	}
